# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-eBay
version:      0.46
version_from: lib/Net/eBay.pm
installdirs:  site
requires:
    Crypt::SSLeay:                 0
    Data::Dumper:                  0
    DateTime::Precise:             0
    HTML::FormatText:              0
    HTML::PrettyPrinter:           0
    HTML::TreeBuilder:             0
    HTTP::Date:                    0
    HTTP::Request::Common:         0
    HTTP::Status:                  0
    LWP::UserAgent:                0
    Net::SSLeay:                   0
    Test::More:                    0
    XML::Dumper:                   0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
